version: "3.9"
services:
  database:
    image: "postgres"
    env_file:
      - ./env/database.env
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./env/pgadmin.env
    volumes:
      - pgadmin:/var/lib/pgadmin4
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - database

  backend:
    build: backend/
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - database

volumes:
  postgres:
  pgadmin:
